# Generated by Django 4.2.7 on 2024-03-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_rename_firstname_member_name_member_join_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine_basic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=255)),
                ('manufacturer_name', models.CharField(max_length=255)),
                ('expiry_date', models.DateTimeField()),
                ('name_of_medicine', models.CharField(max_length=255)),
            ],
        ),
    ]
