# Generated by Django 4.2.7 on 2024-03-13 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_medicine_basic'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine_basic',
            name='test_status',
            field=models.BooleanField(default=False),
        ),
    ]
