# Generated by Django 4.2.7 on 2024-03-14 04:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_medicine_basic_test_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine_basic',
            name='date_of_testing',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
